### ISSUE TITLE
!python conf "schema=st(field(fundcode,string),field(f_rank,float))";python设置数字格式输出，java报错

### ISSUE THREAD

**Issue by zorro-gridi** [byzer-org/kolo-lang#1558] opened 2021-09-23 11:21 UTC
Error: Error while decoding: java.lang.UnsupportedOperationException
createexternalrow(input[0, string, true].toString, input[1, float, true], StructField(fundcode,StringType,true), StructField(f_rank,FloatType,true))
java.lang.RuntimeException: Error while decoding: java.lang.UnsupportedOperationException
createexternalrow(input[0, string, true].toString, input[1, float, true], StructField(fundcode,StringType,true), StructField(f_rank,FloatType,true))
org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.fromRow(ExpressionEncoder.scala:305)

**Comment by allwefantasy** [comment] 2021-09-24 10:03
Can you provide the  code which we can reproduce the problem?

**Comment by hellozepp** [comment] 2022-01-05 06:59
@zorroli93 
I tried to reproduce this problem through code:
```
--NaiveBayes
set jsonStr='''
{"top":{"a":"1","b":"2"},"label":"0.0"},
{"top":{"a":"1","b":"2"},"label":"0.0"}
''';
load jsonStr.`jsonStr` as data;

!python env "PYTHON_ENV=source activate ray1.8.0";
--!python conf "schema=st(field(top,st(field(a,string)))";
!python conf "schema=st(field(fundcode,string),field(f_rank,float))";
!python conf "runIn=driver";
!python conf "dataMode=model";

run command as Ray. `` where
inputTable="data"
and outputTable="output"
and code='''
from pyjava.api.mlsql import RayContext, PythonContext
ray_context = RayContext.connect(globals(),None)
ray_context.build_result([{"fundcode": "jackm", "f_rank": float(1.1)}])
''';
```
The error is as follows:
```

java.lang.RuntimeException: Error while decoding: java.lang.UnsupportedOperationException
createexternalrow(input[0, string, true].toString, input[1, float, true], StructField(fundcode,StringType,true), StructField(f_rank,FloatType,true))
at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:186)
at tech.mlsql.ets.Ray.$anonfun$distribute_execute$20(Ray.scala:182)
at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
at scala.collection.Iterator$$anon$11.next(Iterator.scala:494)
at scala.collection.Iterator.foreach(Iterator.scala:941)
at scala.collection.Iterator.foreach$(Iterator.scala:941)
at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
at scala.collection.TraversableOnce.to(TraversableOnce.scala:315)
at scala.collection.TraversableOnce.to$(TraversableOnce.scala:313)
at scala.collection.AbstractIterator.to(Iterator.scala:1429)
at scala.collection.TraversableOnce.toList(TraversableOnce.scala:299)
at scala.collection.TraversableOnce.toList$(TraversableOnce.scala:299)
at scala.collection.AbstractIterator.toList(Iterator.scala:1429)
at tech.mlsql.ets.Ray.distribute_execute(Ray.scala:180)
at tech.mlsql.ets.Ray.train(Ray.scala:56)
at tech.mlsql.dsl.adaptor.TrainAdaptor.parse(TrainAdaptor.scala:116)
at streaming.dsl.ScriptSQLExecListener.execute$1(ScriptSQLExec.scala:408)
at streaming.dsl.ScriptSQLExecListener.exitSql(ScriptSQLExec.scala:447)
at streaming.dsl.parser.DSLSQLParser$SqlContext.exitRule(DSLSQLParser.java:296)
at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:47)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:30)
at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:28)
at streaming.dsl.ScriptSQLExec$._parse(ScriptSQLExec.scala:160)
at streaming.dsl.ScriptSQLExec$.parse(ScriptSQLExec.scala:147)
at streaming.rest.RestController.$anonfun$script$1(RestController.scala:153)
at tech.mlsql.job.JobManager$.run(JobManager.scala:74)
at tech.mlsql.job.JobManager$$anon$1.run(JobManager.scala:91)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException
at org.apache.spark.sql.vectorized.ArrowColumnVector$ArrowVectorAccessor.getFloat(ArrowColumnVector.java:220)
at org.apache.spark.sql.vectorized.ArrowColumnVector.getFloat(ArrowColumnVector.java:91)
at org.apache.spark.sql.vectorized.ColumnarBatchRow.getFloat(ColumnarBatch.java:208)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Deserializer.apply(ExpressionEncoder.scala:182)
... 33 more
```
It seems that the output as a float is not well parsed, I try to troubleshoot it.

**Comment by hellozepp** [comment] 2022-01-05 10:12
@zorroli93 Since there is no difference between single-precision and double-precision floating-point numbers in python, float is used uniformly, but the actual size is 8 bytes, which will be converted to double type.
Please set it to double in the schema, for example:
```
!python conf "schema=st(field(fundcode,string),field(f_rank,double))";
```

**Comment by chncaesar** [comment] 2022-01-05 13:54
Close the issue as solution is provided

**Closed as completed by chncaesar** 2022-01-05 13:54 UTC

**Comment by allwefantasy** [comment] 2022-01-05 15:07
Also notice that we can use long instead of integer or short 。 can we add some pages in our docs to point out this issues 
？

**Comment by hellozepp** [comment] 2022-01-06 03:01
yes,I will add it in `byzer-doc`
