### ISSUE TITLE
CustomFs header mismatch when i chose `implClass`='csv'.

### ISSUE THREAD

**Issue by AdmondGuo** [byzer-org/kolo-lang#1680] opened 2022-01-28 09:06 UTC
I set config `header` = "true"/ `implClass`="csv" both save and load files to Azure Blob. But the header mismatch when I chose 'csv' implClass.
result like:
<img width="988" alt="截屏2022-01-28 下午5 03 48" src="https://user-images.githubusercontent.com/38072215/151518047-1e309c46-a675-448c-9f0f-633928dae676.png">
It seems that the header setting does not take effect when uploading, but it takes effect when downloading.

**Comment by chncaesar** [comment] 2022-02-23 10:49
Duplicate of #1679

**Closed as completed by chncaesar** 2022-02-23 10:49 UTC

**Comment by AdmondGuo** [comment] 2022-02-23 10:53
The problem comes from spark configuration. Refer this doc: 
[https://spark.apache.org/docs/3.2.1/sql-data-sources-csv.html](https://spark.apache.org/docs/3.2.1/sql-data-sources-csv.html)
Just set multiLine = "true" and you can fix it.
