### ISSUE TITLE
支持 Oracle upsert 语义

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [byzer-org/kolo-lang#1772] opened 2022-04-28 09:46 UTC
详情见 https://github.com/byzer-org/byzer-lang/wiki/BIP-2:-Support-upserting-oracle-table

PR 见 https://github.com/byzer-org/byzer-lang/pull/1722

**Comment by chncaesar** [comment] 2022-05-03 05:27
duplicate of #1718

**Closed as completed by chncaesar** 2022-05-03 05:27 UTC
Labels: byzer-lang 2.3.0
